---
- name: create cluster-admin user context
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:
    - name: Create cluster-admin user context
      shell: kubectl config set-context {{ context_name }} --user=cluster-admin --cluster={{ cluster_name }}
