all:
  hosts:
    node1:
      ansible_host: 192.168.55.180
      ip: 192.168.55.180
      ansible_user: ubuntu
      ansible_become_pass: ubuntu
    node2:
      ansible_host: 192.168.55.190
      ip: 192.168.55.190
      ansible_user: ubuntu
      ansible_become_pass: ubuntu
    node3:
      ansible_host: 192.168.55.200
      ip: 192.168.55.200
      ansible_user: ubuntu
      ansible_become_pass: ubuntu
