all:
  hosts:
    localhost:
      ansible_connection: local
    node1:
      ansible_host: 192.168.55.220
      ip: 192.168.55.220
      access_ip: 192.168.55.220
      ansible_user: ubuntu
      ansible_become_pass: ubuntu
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node: