---
# tasks file for openebs
- name: install open-iscsi
  apt:
    name: open-iscsi
    state: present
    update_cache: yes

- name: restart open-iscsi service
  service:
    name: open-iscsi
    state: restarted

- name: install OpenEBS on Kubernetes cluster with Helm
  helm:
    chart:
      name: "{{ helm.chart.name }}"
      version: "{{ helm.chart.version }}"
      source:
        type: "{{ helm.chart.source.type }}"
        location: "{{ helm.chart.source.location }}"
    name: "{{ helm.name }}"
    namespace: "{{ helm.namespace }}"
    host: "{{ helm.host }}"
    port: "{{ helm.port }}"
